version: "3"

services:
  etcd:
    image: bitnami/etcd:3.5.0
    user: root
    restart: always
    volumes:
      - ./etcd/conf/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
      - ./etcd/home:/bitnami/etcd/
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
    - "2379:2379/tcp"
    - "2380:2380/tcp"
    networks:
      xtc:
        ipv4_address: 10.1.1.21

  apisix-dashboard:
    image: apache/apisix-dashboard:2.7
    restart: always
    volumes:
    - ./apisix-dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      xtc:
        ipv4_address: 10.1.250.11

  apisix:
    image: apache/apisix:2.7-alpine
    restart: always
    volumes:
      - ./apisix/log:/usr/local/apisix/logs
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
    networks:
      xtc:
        ipv4_address: 10.1.254.11

  mysql:
    image: mysql:8.0.26
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql@XTC"
    networks:
      xtc:
        ipv4_address: 10.1.2.11

  mongo:
    image: mongo:5.0.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    networks:
      xtc:
        ipv4_address: 10.1.2.21

  redis:
    image: redis:6.2.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      xtc:
        ipv4_address: 10.1.2.31

  ogm-sandbox:
    image: xtechcloud/ogm-sandbox:v3.12
    restart: always
    ports:
      - "8822:22"
      - "18801-18899:18801-18899"
    volumes:
      - ./ogm-sandbox:/ogm
    environment:
      MSA_REGISTRY_PLUGIN: "etcd"
      MSA_REGISTRY_ADDRESS: "etcd:2379"
    networks:
      xtc:
        ipv4_address: 10.1.100.11
    links:
      - etcd:etcd
      - mysql:mysql
      - mongo:mongo
      - redis:redis
    depends_on:
      - etcd

networks:
  xtc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/16
