version: "3"

services:

  mysql:
    image: mysql:8.0.26
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql@XTC"
    networks:
      xtc:
        ipv4_address: 192.1.2.11

  mongo:
    image: mongo:5.0.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    networks:
      xtc:
        ipv4_address: 192.1.2.21

  redis:
    image: redis:6.2.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      xtc:
        ipv4_address: 192.1.2.31

  minio:
    image: minio/minio:RELEASE.2021-07-27T02-40-15Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: "3KJLIOSFODNN0EXAMPO0"
      MINIO_ROOT_PASSWORD: "vJalrXUtnFEMI/I5MDENG/bPxRfmCYEXAMPLEHEY"
    command: server /data --console-address ":9001"
    networks:
      xtc:
        ipv4_address: 192.1.2.41

networks:
  xtc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.1.2.0/24
