version: "3"

services:
  etcd:
    image: bitnami/etcd:3.5.0
    user: root
    restart: always
    volumes:
      - ./etcd/conf/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
      - ./etcd/home:/bitnami/etcd/
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
    - "2379:2379/tcp"
    - "2380:2380/tcp"
    networks:
      xtc:
        ipv4_address: 10.1.1.11

  apisix-dashboard:
    image: apache/apisix-dashboard:2.8
    restart: always
    volumes:
    - ./apisix-dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - apisix
    ports:
    - "9999:9000"
    networks:
      xtc:
        ipv4_address: 10.1.250.11

  apisix:
    image: apache/apisix:2.9-alpine
    restart: always
    volumes:
      - ./apisix/log:/usr/local/apisix/logs
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
    links:
      - etcd:etcd
    networks:
      xtc:
        ipv4_address: 10.1.254.11

  mysql:
    image: mysql:8.0.26
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql@XTC"
    networks:
      xtc:
        ipv4_address: 10.1.2.11

  mongo:
    image: mongo:5.0.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    networks:
      xtc:
        ipv4_address: 10.1.2.21

  redis:
    image: redis:6.2.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      xtc:
        ipv4_address: 10.1.2.31

  minio:
    image: minio/minio:RELEASE.2021-07-27T02-40-15Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: "3KJLIOSFODNN0EXAMPO0"
      MINIO_ROOT_PASSWORD: "vJalrXUtnFEMI/I5MDENG/bPxRfmCYEXAMPLEHEY"
    command: server /data --console-address ":9001"
    networks:
      xtc:
        ipv4_address: 10.1.2.41

  ogm-license:
    image: xtechcloud/ogm-license:v3.0.1
    restart: always
    ports:
      - "18804:18804"
    volumes:
      - ./ogm-config/license.yml:/etc/ogm/license.yml
    links:
      - etcd:etcd
      - mysql:mysql
    environment:
      MSA_CONFIG_DEFINE: '{"source":"file","prefix":"/etc/ogm/","key":"license.yml"}'
    networks:
      xtc:
        ipv4_address: 10.1.188.4

networks:
  xtc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/16
