version: "3"

services:
  etcd:
    image: bitnami/etcd:3.5.0
    user: root
    restart: always
    volumes:
      - ./etcd/conf/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
      - ./etcd/home:/bitnami/etcd/
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
    - "2379:2379/tcp"
    - "2380:2380/tcp"
    networks:
      xtc:
        ipv4_address: 192.1.1.11

networks:
  xtc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.1.1.0/24
