version: "3"

services:

  apisix:
    image: apache/apisix:2.9-alpine
    restart: always
    volumes:
      - ./apisix/log:/usr/local/apisix/logs
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
    links:
      - etcd:etcd
    networks:
      xtc:
        ipv4_address: 192.1.254.11

networks:
  xtc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.1.254.0/24
